### ISSUE TITLE
NameError: name 'crypto' is not defined

### ISSUE THREAD

**Issue by Waffaru** [Adam-Langley/pybleno#36] opened 2019-06-18 10:27 UTC
Hello, I am using pybleno on a Raspberry pi 3. I've set up the echo example and run the script. The device advertises fine, but when I try to establish a connection using my phone, I get the following stacktrace:

```
Exception in thread HCISocketPoller:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pybleno/hci_socket/BluetoothHCI/BluetoothHCI.py", line 197, in _socket_poller
    self._socket_on_data_user_callback(bytearray(data))
  File "/usr/local/lib/python3.5/dist-packages/pybleno/hci_socket/Hci.py", line 414, in onSocketData
    self.emit('aclDataPkt', [handle, cid, pktData])
  File "/usr/local/lib/python3.5/dist-packages/pybleno/hci_socket/Emit.py", line 17, in emit
    handler(*arguments)
  File "/usr/local/lib/python3.5/dist-packages/pybleno/hci_socket/Bindings.py", line 169, in onAclDataPkt
    self._aclStream.push(cid, data)
  File "/usr/local/lib/python3.5/dist-packages/pybleno/hci_socket/AclStream.py", line 18, in push
    self.emit('data', [cid, data])
  File "/usr/local/lib/python3.5/dist-packages/pybleno/hci_socket/Emit.py", line 17, in emit
    handler(*arguments)
  File "/usr/local/lib/python3.5/dist-packages/pybleno/hci_socket/Smp.py", line 48, in onAclStreamData
    self.handlePairingConfirm(data)
  File "/usr/local/lib/python3.5/dist-packages/pybleno/hci_socket/Smp.py", line 101, in handlePairingConfirm
    self._r = crypto.r()
NameError: name 'crypto' is not defined
```
I'm not sure what's causing the issue, any help would be appreciated.

**Comment by Adam-Langley** [comment] 2019-06-18 22:25
Hi @Waffaru - the crypto module is not currently implemented - it's in the works however and should be available soon.
Duplicate of #9

**Closed by Adam-Langley** 2019-06-18 22:25 UTC
